config/routes.rb
Lotr::Application.routes.draw do
  resources :creature_histories

  resources :event_logs

  resources :creatures do 
    collection do
      post 'execute_event'
    end
  end

  get "home/index"

   root :to => 'home#index'

end

app/models/event_log.rb
class EventLog < ActiveRecord::Base
  attr_accessible :annotation, :created_at, :created_by, :event, :reference_id, :reference_type
    validates_presence_of :reference_id, :reference_type
    belongs_to :reference, polymorphic: true
    belongs_to :creator, class_name: Creature, foreign_key: :created_by, primary_key: 'id'

    has_many :creature_histories
    after_create :snapshot 

    def snapshot
    	Creature.all.each do |c|
    		self.creature_histories << CreatureHistory.create(event_log_id: self.id, creature_id: c.id, latitude: c.latitude, longitude: c.longitude, is_alive: c.is_alive, has_ring: c.has_ring)
    	end
    end
end

app/controllers/event_logs_controller.rb
class EventLogsController < ApplicationController
  # GET /event_logs
  # GET /event_logs.json
  def index
    @event_logs = EventLog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_logs }
    end
  end

  # GET /event_logs/1
  # GET /event_logs/1.json
  def show
    @event_log = EventLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_log }
    end
  end

  # GET /event_logs/new
  # GET /event_logs/new.json
  def new
    @event_log = EventLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_log }
    end
  end

  # GET /event_logs/1/edit
  def edit
    @event_log = EventLog.find(params[:id])
  end

  # POST /event_logs
  # POST /event_logs.json
  def create
    @event_log = EventLog.new(params[:event_log])

    respond_to do |format|
      if @event_log.save
        format.html { redirect_to @event_log, notice: 'Event log was successfully created.' }
        format.json { render json: @event_log, status: :created, location: @event_log }
      else
        format.html { render action: "new" }
        format.json { render json: @event_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_logs/1
  # PUT /event_logs/1.json
  def update
    @event_log = EventLog.find(params[:id])

    respond_to do |format|
      if @event_log.update_attributes(params[:event_log])
        format.html { redirect_to @event_log, notice: 'Event log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_logs/1
  # DELETE /event_logs/1.json
  def destroy
    @event_log = EventLog.find(params[:id])
    @event_log.destroy

    respond_to do |format|
      format.html { redirect_to event_logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/event_logs_helper.rb
module EventLogsHelper
end

app/views/event_logs/_form.html.erb
<%= form_for(@event_log) do |f| %>
  <% if @event_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_log.errors.count, "error") %> prohibited this event_log from being saved:</h2>

      <ul>
      <% @event_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :annotation %><br />
    <%= f.text_field :annotation %>
  </div>
  <div class="field">
    <%= f.label :reference_id %><br />
    <%= f.number_field :reference_id %>
  </div>
  <div class="field">
    <%= f.label :reference_type %><br />
    <%= f.text_field :reference_type %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.number_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_logs/edit.html.erb
<h1>Editing event_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_log %> |
<%= link_to 'Back', event_logs_path %>

app/views/event_logs/index.html.erb
<%= link_to 'home', root_path %>
<%= link_to "Creatures", creatures_path %>
<%= link_to "Creature History", creature_histories_path %>
<h1>Listing event_logs</h1>
<h3> Ring's latitude: <%= Ring.instance.latitude %></h3>
<h3> Ring's longitude: <%= Ring.instance.longitude %></h3>
<br />
<br />

<% if @event_logs.present? %>
<table>
  <tr>
    <th>Id</th>
    <th>Event</th>
    <th>Annotation</th>
    <th>Reference</th>
    <th>Reference type</th>
    <th>Created at</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_logs.each do |event_log| %>
  <tr>
    <td><%= event_log.id %></td>
    <td><%= event_log.event %></td>
    <td><%= event_log.annotation %></td>
    <td><%= event_log.reference_id %></td>
    <td><%= event_log.reference_type %></td>
    <td><%= event_log.created_at %></td>
    <td><%= event_log.creator.name %></td>
    <td><%#= link_to 'Show', event_log %></td>
    <td><%#= link_to 'Edit', edit_event_log_path(event_log) %></td>
    <td><%#= link_to 'Destroy', event_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<% else %>
    No Event Logs Exists. Please <%= link_to 'Create New Creature', new_creature_path %> first!
<% end %>

<br />

<%#= link_to 'New Event log', new_event_log_path %>

app/views/event_logs/new.html.erb
<h1>New event_log</h1>

<%= render 'form' %>

<%= link_to 'Back', event_logs_path %>

app/views/event_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event_log.event %>
</p>

<p>
  <b>Annotation:</b>
  <%= @event_log.annotation %>
</p>

<p>
  <b>Reference:</b>
  <%= @event_log.reference_id %>
</p>

<p>
  <b>Reference type:</b>
  <%= @event_log.reference_type %>
</p>

<p>
  <b>Created at:</b>
  <%= @event_log.created_at %>
</p>

<p>
  <b>Created by:</b>
  <%= @event_log.created_by %>
</p>


<%= link_to 'Edit', edit_event_log_path(@event_log) %> |
<%= link_to 'Back', event_logs_path %>