config/routes.rb
Lotr::Application.routes.draw do
  resources :creature_histories

  resources :event_logs

  resources :creatures do 
    collection do
      post 'execute_event'
    end
  end

  get "home/index"

   root :to => 'home#index'

end

app/models/creature.rb
class Creature < ActiveRecord::Base
  attr_accessible :has_ring, :is_alive, :latitude, :longitude, :name
  attr_accessor :current_event, :updated_by
  validates_presence_of :latitude, :longitude, :name

  has_many :history, class_name: CreatureHistory.name, foreign_key: 'creature_id'
  has_many :event_logs, class_name: EventLog.name, as: :reference

  #before_save :check_ring_creature
  after_create :check_ring_and_create_event_log
  after_update :create_event_log
  after_save :fix_ring_position

  def check_ring_and_create_event_log
    self.has_ring = true if !self.has_ring? && self.close_to_ring? && Ring.instance.alone?
    create_event_log
  end

  def close_to_ring?
    r = Ring.instance
    self.latitude == r.latitude && self.longitude == r.longitude
  end
  def check_ring_creature
    #cs = Creature.where(has_ring: true)
    #rc = cs.first
    #if !rc.blank? && has_ring_changed? && :has_ring == true
    #  rc.update_attribute(:has_ring, false)
    #end
    #if !is_alive? && has_ring?
    #  fc = Creature.where(is_alive: true, latitude: self.latitude, longitude: self.longitude).first
    #  if fc.blank?
    #    raise Exception.new("Ring is alone.")
    #  else
    #    fc.update_attribute(:has_ring, true)
    #  end
    #end
  	# if cs.count != 1
  	# 	errors.add(:has_ring, "Ring must be assign to exactly one creature.")
  	# elsif rc.latitude != Ring.instance.latitude || rc.longitude == Ring.instance.longitude
  	# 	errors.add(:has_ring, "Ring position shoould be matched with the creature which has it.")
  	# end
  end

  def create_event_log
    self.current_event = Creature.event[:comes_in] if self.current_event.blank?
    el_cid = self.id
    el_cid = self.updated_by if self.current_event == :dead && !self.updated_by.blank?
  	self.event_logs << EventLog.create(event: self.current_event, annotation: "#{self.name} #{self.current_event}.", reference_id: self.id, reference_type: self.class.name, created_by: el_cid)
  end

  def fix_ring_position
    r = Ring.instance
    if self.has_ring?
      if self.is_alive?
        if !r.alone? && self != r.creature
          r.creature.current_event = self.current_event
          r.creature.updated_by = self.id
          r.creature.update_attribute(:has_ring, false)
        end
        r.position(self.latitude, self.longitude, self.id)
      elsif !self.updated_by.blank?
        k = Creature.where(id: self.updated_by).first
        if k.close_to_ring?
          r.position(k.latitude, k.longitude, k.id)
        else
          rc = Creature.where(is_alive: true, latitude: r.latitude, longitude: r.longitude).first
          r.update_attribute(:updated_by, rc.blank? ? -1 : rc.id)
        end
      else
        rc = Creature.where(is_alive: true, latitude: r.latitude, longitude: r.longitude).first
        r.update_attribute(:updated_by, rc.blank? ? -1 : rc.id)
      end
    end
  end

  def update_position lat, lon
    self.latitude = lat
    self.longitude = lon
    self.save!
  end

  def update_death kid
    self.updated_by = kid
    self.update_attribute(:is_alive, false)
  end

  def update_ring_creature
    self.update_attribute(:has_ring, true) if self.is_alive?
  end

  class << self
  	attr_reader :event

    def ring_creature
      Creature.where(is_alive: true, has_ring: true).first
    end
  end

  @event = {
  	comes_in: "Comes In",
  	goes_away: "Goes Away",
  	receive_ring: "Receive Ring",
  	died: "Died",
  	change_position: "Change Position"
  }.freeze

end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  # GET /creatures
  # GET /creatures.json
  def index
    @creatures = Creature.all
    @events = Creature.event.except(:comes_in)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @creatures }
    end
  end

  # GET /creatures/1
  # GET /creatures/1.json
  def show
    @creature = Creature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @creature }
    end
  end

  # GET /creatures/new
  # GET /creatures/new.json
  def new
    r = Ring.instance
    @creature = Creature.new(latitude: r.latitude, longitude: r.longitude)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @creature }
    end
  end

  # GET /creatures/1/edit
  def edit
    @creature = Creature.find(params[:id])
  end

  # POST /creatures
  # POST /creatures.json
  def create
    @creature = Creature.new(params[:creature])

    respond_to do |format|
      if @creature.save
        format.html { redirect_to @creature, notice: 'Creature was successfully created.' }
        format.json { render json: @creature, status: :created, location: @creature }
      else
        format.html { render action: "new" }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /creatures/1
  # PUT /creatures/1.json
  def update
    @creature = Creature.find(params[:id])

    respond_to do |format|
      if @creature.update_attributes(params[:creature])
        format.html { redirect_to @creature, notice: 'Creature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatures/1
  # DELETE /creatures/1.json
  def destroy
    @creature = Creature.find(params[:id])
    @creature.destroy

    respond_to do |format|
      format.html { redirect_to creatures_url }
      format.json { head :no_content }
    end
  end

  def execute_event
    lat = params[:latitude].to_f
    lon = params[:longitude].to_f
    e = params[:event].to_sym
    cid = params[:cid]
    kid = params[:killed_by]
    r = Ring.instance
    errors = []
    creatures = []
    if !cid.blank?
      c = Creature.where(id: cid).first
      if c.has_ring?
        raise Exception.new("Please transfer the ring to someone else before going away.") if :goes_away == e
        raise Exception.new("Already have the ring with You.") if :receive_ring == e
      end
      creatures << c
    elsif e == :change_position
      creatures = Creature.where(latitude: r.latitude, longitude: r.longitude, is_alive: true)
    end

    creatures.each do |c|
      c.current_event = Creature.event[e]
      puts "==============#{c.current_event} is getting executed for #{c.name}=============="
      c.update_death kid if :died == e
      c.update_ring_creature if e == :receive_ring
      c.update_position(lat, lon) if [:change_position, :goes_away].include? e

      if c.errors.present?
        errors << c.errors
        raise Exception.new(errors.join(", "))
      end
    end

    respond_to do |format|
      if errors.blank?
        flash[:success]="#{Creature.event[:event]} was successful."
        format.html { redirect_to creatures_url, notice: '#{Creature.event[:event]} was successful.' }
        format.json { head :no_content }
      else
        flash[:error]="#{errors.join(",")} so #{Creature.event[:event]} was failled."
        format.html { redirect_to creatures_url, error: '#{errors.join(",")} so #{Creature.event[:event]} was failled.' }
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/_form.html.erb
<%= form_for(@creature) do |f| %>
  <% if @creature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creature.errors.count, "error") %> prohibited this creature from being saved:</h2>

      <ul>
      <% @creature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :is_alive %><br />
    <%= f.check_box :is_alive %>
  </div>
  <div class="field">
    <%= f.label :has_ring %><br />
    <%= f.check_box :has_ring %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/creatures/_killer_form.html.erb
<%= form_tag url_for("/creatures/execute_event"), onsubmit: "return validate_killer_id(this)" do |f| %>
    <table>
      <tr>
      	<td><%= hidden_field_tag 'event', @event  %></td>
      	<td><%= hidden_field_tag 'cid', @cid  %></td>
        <td><%= text_field_tag "killed_by", nil, :placeholder => "Enter Killer Id", :class => 'input-small' %></td>

        <td><%= submit_tag 'Execute', class: 'btn btn-success' %></td>
       </tr>
    </table>
<% end %>


<script type="text/javascript">
    function validate_killer_id(thisObj) {
        var killer_id = $(thisObj).children().siblings('table').children().children().children().siblings().children('input#killed_by').val();
        alert(killer_id)
        if (killer_id == undefined || killer_id == "") {
            alert('Invalid Killer Id');
            return false;
        }
        $(thiObj).parent().hide();
        alert(killer_id)
        return false;
//        return true;
    }
</script>

app/views/creatures/_position_form.html.erb
<%= form_tag url_for("/creatures/execute_event"), onsubmit: "return validate_fields(this)" do |f| %>
    <table>
      <tr>
      	<td><%= hidden_field_tag 'event', @event  %></td>
      	<td><%= hidden_field_tag 'cid', @cid  %></td>
        <td><%= text_field_tag "latitude", nil, :placeholder => "Enter latitude", :class => 'input-small' %></td>
        <td><%= text_field_tag "longitude", nil, :placeholder => "Enter longitude", :class => 'input-small' %></td>

        <td><%= submit_tag 'Execute', class: 'btn btn-success' %></td>
       </tr>
    </table>
<% end %>


<script type="text/javascript">
    function validate_fields(thisObj) {
        var latitude = $(thisObj).children().siblings('table').children().children().children().siblings().children('input#latitude').val();
        var longitude = $(thisObj).children().siblings('table').children().children().children().siblings().children('input#longitude').val();
        if (latitude == undefined || latitude == "") {
            alert('Invalid latitude');
            return false;
        }else if (longitude == undefined || longitude == "") {
            alert('Invalid longitude');
            return false;
        }
        $(thiObj).parent().hide();
        return true;
    }
</script>

app/views/creatures/edit.html.erb
<h1>Editing creature</h1>

<%= render 'form' %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

app/views/creatures/index.html.erb
<%= link_to 'home', root_path %>
<%= link_to "Creature History", creature_histories_path %>
<%= link_to "Event Logs", event_logs_path %>
<h1>Listing creatures</h1>
<h3>
  <% if Ring.instance.alone? %>
      Ring is Alone.
  <% else %>
      Ring is with <%= Ring.instance.creature.name %>
  <% end %>
</h3>
<h3> Ring's latitude: <%= Ring.instance.latitude %></h3>
<h3> Ring's longitude: <%= Ring.instance.longitude %></h3>
<%= link_to 'Create New Creature', new_creature_path %>
<br />
<br />

<script type="text/javascript">
    function showEventHelperForm(div_id, ev, cid) {
        e=ev
        if(div_id.startsWith('event_div') ) {
            $('.event_td').children().hide()
            e = $('#' + ev).val();

            if(e == 'receive_ring') {
                var r=confirm("Creature Id "+ cid + " " + e + ". Are you sure you want to do this ?")
                if (r== true){
                    $.ajax({
                      type: "POST",
                      url: "/creatures/execute_event",
                      data: { "cid": cid, "event": e},
                      success:function(data) {
                        alert("Marked Creature Id " +cid +" " + e + ". Successfully. Please refresh the page.");
                        return true
                      },
                      error: function(data){
                        alert("Not able to mark Creature Id " +cid +" " + e);
                        return false;
                      }
                    })
                }
            } else {
                $("#" + "event_div" + cid + "_" + e).show()
            }
        } else {
            $("#" + div_id).show();
        }
//        alert(div_id + ev + cid)
    }
</script>

<% if @creatures.present? %>
    <%= hidden_field_tag 'event', 'change_position'  %>
    <%= hidden_field_tag 'cid', ''  %>
    <input type="button" value="Change Ring Position" onclick="showEventHelperForm('bulk_event_div', 'change_position', '')"/>
    <div id="bulk_event_div" style="display:none">
      <%= render :partial => 'position_form', :locals => {:'@event'=> 'change_position', :'@cid' => ''} %>
    </div>
    <br />
    <br/>
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Is alive</th>
    <th>Has ring</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @creatures.each do |creature| %>
      <tr>
        <td><%= creature.id %></td>
        <td><%= creature.name %></td>
        <td><%= creature.latitude %></td>
        <td><%= creature.longitude %></td>
        <td><%= creature.is_alive %></td>
        <td><%= creature.has_ring %></td>
        <td><%#= link_to 'Show', creature %></td>
        <td><%#= link_to 'Edit', edit_creature_path(creature) %></td>
        <td><%= hidden_field_tag 'event', 'change_position'  %></td>
        <td><%= hidden_field_tag 'cid', ''  %></td>
        <td>
          <% if creature.is_alive %>
              <%= select("#{creature.id}", "event", @events.map { |k,v|
                #creature with ring cannot execute receive ring & can not goes away
                #creature with different position as ring cannot execute receive ring
                if (creature.has_ring? && [:receive_ring, :goes_away].include?(k)) || (k == :receive_ring && !creature.has_ring? && (creature.latitude.to_f != Ring.instance.latitude.to_f || creature.longitude.to_f != Ring.instance.longitude.to_f))
                  ['-','-']
                else
                  [v, k]
                end
              }, {include_blank: '-- Select Event --'}, onchange: "showEventHelperForm('event_div#{creature.id}','#{creature.id}_event', '#{creature.id}')") %>
          <% else %>
              Died on <%= creature.updated_at %>
          <% end %>
        </td>
        <td class="event_td">
          <%@events.map do |k,v|  %>
              <% if (creature.has_ring? && [:receive_ring, :goes_away].include?(k)) || (k == :receive_ring && !creature.has_ring? && (creature.latitude.to_f != Ring.instance.latitude.to_f || creature.longitude.to_f != Ring.instance.longitude.to_f)) %>

              <% elsif k == :died %>
                  <div id="event_div<%=creature.id%>_<%=k%>" style="display:none">
                    <%= render :partial => 'killer_form', :locals => {:'@event'=> k, :'@cid' => creature.id} %>
                  </div>
              <% else %>
                  <div id="event_div<%=creature.id%>_<%=k%>" style="display:none">
                    <%= render :partial => 'position_form', :locals => {:'@event'=> k, :'@cid' => creature.id} %>
                  </div>
              <% end %>
          <% end %>
        </td>
        <td><%#= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<%else%>
    No Creature Exists. Please <%= link_to 'Create New Creature', new_creature_path %> first!
<% end %>

app/views/creatures/new.html.erb
<%= link_to 'home', root_path %>
<h3> Ring's latitude: <%= Ring.instance.latitude %></h3>
<h3> Ring's longitude: <%= Ring.instance.longitude %></h3>
<h1>New creature</h1>
<br />
<br />

<%= render 'form' %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.erb
<%= link_to 'home', root_path %>
<%= link_to "Creatures", creatures_path %>
<%= link_to "Creature History", creature_histories_path %>
<%= link_to "Event Logs", event_logs_path %>
<h3> Ring's latitude: <%= Ring.instance.latitude %></h3>
<h3> Ring's longitude: <%= Ring.instance.longitude %></h3>
<br />
<br />
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @creature.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @creature.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @creature.longitude %>
</p>

<p>
  <b>Is alive:</b>
  <%= @creature.is_alive %>
</p>

<p>
  <b>Has ring:</b>
  <%= @creature.has_ring %>
</p>


<%#= link_to 'Edit', edit_creature_path(@creature) %> |
<%= link_to 'Back', creatures_path %>