config/routes.rb
Lotr::Application.routes.draw do
  resources :creature_histories

  resources :event_logs

  resources :creatures do 
    collection do
      post 'execute_event'
    end
  end

  get "home/index"

   root :to => 'home#index'

end

app/models/creature_history.rb
class CreatureHistory < ActiveRecord::Base
  attr_accessible :created_at, :creature_id, :event_log_id, :has_ring, :is_alive, :latitude, :longitude
  validates_presence_of :creature_id, :event_log_id

  belongs_to :event_log
  belongs_to :creature
end

app/controllers/creature_histories_controller.rb
class CreatureHistoriesController < ApplicationController
  # GET /creature_histories
  # GET /creature_histories.json
  def index
    @creature_histories = CreatureHistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @creature_histories }
    end
  end

  # GET /creature_histories/1
  # GET /creature_histories/1.json
  def show
    @creature_history = CreatureHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @creature_history }
    end
  end

  # GET /creature_histories/new
  # GET /creature_histories/new.json
  def new
    @creature_history = CreatureHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @creature_history }
    end
  end

  # GET /creature_histories/1/edit
  def edit
    @creature_history = CreatureHistory.find(params[:id])
  end

  # POST /creature_histories
  # POST /creature_histories.json
  def create
    @creature_history = CreatureHistory.new(params[:creature_history])

    respond_to do |format|
      if @creature_history.save
        format.html { redirect_to @creature_history, notice: 'Creature history was successfully created.' }
        format.json { render json: @creature_history, status: :created, location: @creature_history }
      else
        format.html { render action: "new" }
        format.json { render json: @creature_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /creature_histories/1
  # PUT /creature_histories/1.json
  def update
    @creature_history = CreatureHistory.find(params[:id])

    respond_to do |format|
      if @creature_history.update_attributes(params[:creature_history])
        format.html { redirect_to @creature_history, notice: 'Creature history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @creature_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creature_histories/1
  # DELETE /creature_histories/1.json
  def destroy
    @creature_history = CreatureHistory.find(params[:id])
    @creature_history.destroy

    respond_to do |format|
      format.html { redirect_to creature_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/creature_histories_helper.rb
module CreatureHistoriesHelper
end

app/views/creature_histories/_form.html.erb
<%= form_for(@creature_history) do |f| %>
  <% if @creature_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creature_history.errors.count, "error") %> prohibited this creature_history from being saved:</h2>

      <ul>
      <% @creature_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_log_id %><br />
    <%= f.number_field :event_log_id %>
  </div>
  <div class="field">
    <%= f.label :creature_id %><br />
    <%= f.number_field :creature_id %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :is_alive %><br />
    <%= f.check_box :is_alive %>
  </div>
  <div class="field">
    <%= f.label :has_ring %><br />
    <%= f.check_box :has_ring %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/creature_histories/edit.html.erb
<h1>Editing creature_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @creature_history %> |
<%= link_to 'Back', creature_histories_path %>

app/views/creature_histories/index.html.erb
<%= link_to 'home', root_path %>
<%= link_to "Creatures", creatures_path %>
<%= link_to "Event Logs", event_logs_path %>
<h1>Listing creature_histories</h1>
<h3> Ring's latitude: <%= Ring.instance.latitude %></h3>
<h3> Ring's longitude: <%= Ring.instance.longitude %></h3>
<br />
<br />

<% if @creature_histories.present? %>
<table>
  <tr>
    <th>Id</th>
    <th>Event log</th>
    <th>Creature</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Is alive</th>
    <th>Has ring</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @creature_histories.each do |creature_history| %>
  <tr>
    <td><%= creature_history.id %></td>
    <td><%= creature_history.event_log.annotation %></td>
    <td><%= creature_history.creature.name %></td>
    <td><%= creature_history.latitude %></td>
    <td><%= creature_history.longitude %></td>
    <td><%= creature_history.is_alive %></td>
    <td><%= creature_history.has_ring %></td>
    <td><%= creature_history.created_at %></td>
    <td><%#= link_to 'Show', creature_history %></td>
    <td><%#= link_to 'Edit', edit_creature_history_path(creature_history) %></td>
    <td><%#= link_to 'Destroy', creature_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<% else %>
    No Creature History Exists. Please <%= link_to 'Create New Creature', new_creature_path %> first!
<% end %>
<br />

<%#= link_to 'New Creature history', new_creature_history_path %>

app/views/creature_histories/new.html.erb
<h1>New creature_history</h1>

<%= render 'form' %>

<%= link_to 'Back', creature_histories_path %>

app/views/creature_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event log:</b>
  <%= @creature_history.event_log_id %>
</p>

<p>
  <b>Creature:</b>
  <%= @creature_history.creature_id %>
</p>

<p>
  <b>Latitude:</b>
  <%= @creature_history.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @creature_history.longitude %>
</p>

<p>
  <b>Is alive:</b>
  <%= @creature_history.is_alive %>
</p>

<p>
  <b>Has ring:</b>
  <%= @creature_history.has_ring %>
</p>

<p>
  <b>Created at:</b>
  <%= @creature_history.created_at %>
</p>


<%= link_to 'Edit', edit_creature_history_path(@creature_history) %> |
<%= link_to 'Back', creature_histories_path %>